# Generated by Django 6.0.6 on 2026-07-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='blockchain_hash',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='breed',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='species',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='tag_number',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='dosage',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='withdrawal_days',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='BlockchainRecord',
        ),
    ]
