# Generated by Django 6.0.6 on 2026-07-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0002_treatment_blockchain_hash_alter_livestock_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='blockchain_hash',
            field=models.CharField(blank=True, editable=False, max_length=256),
        ),
    ]
