# Generated by Django 6.0.6 on 2026-07-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0003_alter_treatment_blockchain_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='blockchain_hash',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
